##  **Import OEO**

In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

from quinex_application.oeo_data import OEOData

etd_path = "../data/raw/etd.xlsx"
ontology_path = "../data/raw/oeo-full.owl"
output_path = "../data/processed/oeo.xlsx"

oeo = OEOData(etd_path, ontology_path, output_path)
oeo.process_oeo_data()

c:\Users\m.gorres\AppData\Local\miniforge3\envs\quinex_application_env\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,ID,LABEL,definition,URI,Super class
0,OEO:00000047,AC-line,An AC-line is a powerline for transferring hig...,http://openenergy-platform.org/ontology/oeo/OE...,power line
2,OEO:00010126,Annual Emission Allocation,An Annual Emission Allocation (AEA) is an emis...,http://openenergy-platform.org/ontology/oeo/OE...,emission certificate
3,OEO:00010448,B7,B7 is a diesel fuel that consists of fossil di...,http://openenergy-platform.org/ontology/oeo/OE...,diesel fuel
4,OEO:00410014,BNatSchG,The BNatSchG is a legislation providing the le...,http://openenergy-platform.org/ontology/oeo/OE...,None
5,OEO:00360042,BSI-KritisV energy sector,The BSI-KritisV energy sector is an energy tra...,http://openenergy-platform.org/ontology/oeo/OE...,None
...,...,...,...,...,...
1728,UO:0000305,zepto,"""A prefix in the metric system denoting a fact...",http://openenergy-platform.org/ontology/oeo/UO...,None
1729,BFO:0000147,zero-dimensional continuant fiat boundary,NaN,http://openenergy-platform.org/ontology/oeo/BF...,None
1730,BFO:0000018,zero-dimensional spatial region,NaN,http://openenergy-platform.org/ontology/oeo/BF...,None
1731,BFO:0000148,zero-dimensional temporal region,NaN,http://openenergy-platform.org/ontology/oeo/BF...,None
1732,UO:0000288,zetta,"""A prefix in the metric system denoting a fact...",http://openenergy-platform.org/ontology/oeo/UO...,None

In [2]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
oeo = pd.read_excel("../data/processed/oeo.xlsx")
display(oeo.head())

,ID,LABEL,definition,URI,Super class
0,OEO:00000047,AC-line,An AC-line is a powerline for transferring high voltage alternating current.,http://openenergy-platform.org/ontology/oeo/OEO_00000047,power line
1,OEO:00010126,Annual Emission Allocation,An Annual Emission Allocation (AEA) is an emission certificate used in the Effort Sharing Decision (ESD) and the Effort Sharing Regulation (ESR). It permits the emission of a CO2 equivalent quantity of 1 tonne.,http://openenergy-platform.org/ontology/oeo/OEO_00010126,emission certificate
2,OEO:00010448,B7,B7 is a diesel fuel that consists of fossil diesel fuel and up to 7 % biodiesel and that is liquid.,http://openenergy-platform.org/ontology/oeo/OEO_00010448,diesel fuel
3,OEO:00410014,BNatSchG,The BNatSchG is a legislation providing the legal framework for nature conservation and landscape management in Germany.,http://openenergy-platform.org/ontology/oeo/OEO_00410014,NaN
4,OEO:00360042,BSI-KritisV energy sector,The BSI-KritisV energy sector is an energy transformation sector defined by the BSI-KritisV sector division (§ 2 BSI-KritisV).,http://openenergy-platform.org/ontology/oeo/OEO_00360042,NaN

## **Levenshtein Distance**

In [8]:
from quinex_application.levenshtein import LevenshteinDistance

levenshtein = LevenshteinDistance()

top_matches = levenshtein.find_top_matches("emission levels", oeo, levenshtein="extended_similarity")
for label, score in top_matches:
    print(f"🔍 Match: {label} — Score: {score:.2f}")

🔍 Match: CRF sector (IPCC 2006): fugitive emissions from fuels — Score: 0.69
🔍 Match: EU emission sector: ETS — Score: 0.67
🔍 Match: EU emission sector: ETS aviation — Score: 0.67
🔍 Match: EU emission sector: ETS stationary — Score: 0.67
🔍 Match: greenhouse gas emission — Score: 0.60
🔍 Match: greenhouse gas emission rate — Score: 0.60
🔍 Match: greenhouse gas emission scenario — Score: 0.60
🔍 Match: greenhouse gas emission value — Score: 0.60
🔍 Match: total emissions excluding LULUCF and including international bunkers — Score: 0.59
🔍 Match: total emissions including LULUCF and including international bunkers — Score: 0.59
🔍 Match: CO2 emission rate — Score: 0.58
🔍 Match: CO2 emission value — Score: 0.58
🔍 Match: EU emission sector division — Score: 0.58
🔍 Match: EU emission sector: LULUCF — Score: 0.58
🔍 Match: EU emission sector: effort sharing — Score: 0.58
🔍 Match: emission factor value — Score: 0.58
🔍 Match: emission rate — Score: 0.58
🔍 Match: emission value — Score: 0.58
🔍 Match: CO2 emission scenario — Score: 0.56
🔍 Match: emission scenario — Score: 0.56

In [9]:
match, score = levenshtein.get_best_match("emission levels", oeo, levenshtein="extended_similarity", score_limit=0.8)
print(f"🔍 Match: {match} — Score: {score:.2f}")

10.599999999999998
🔍 Match: emission levels — Score: 0.69