### **Setup: Imports und Initialisierung**

In [1]:
import sys
import os

sys.path.append(os.path.abspath('..'))

from quinex_application.quinex_discussion import QuinexDiscussion

In [2]:
discussion = QuinexDiscussion()

### **Load Results**

In [3]:
df_quinex = discussion.load_df("../data/quinex/df_quinex_metadata.parquet")
df_quinex_mapped = discussion.load_df("../data/visualisation_files/general/df_technologies.parquet")
print(f"Proportion of mapped statements: {len(df_quinex)}/{len(df_quinex_mapped)}")

📂 Loaded DataFrame from '../data/quinex/df_quinex_metadata.parquet' with 14170 rows
📂 Loaded DataFrame from '../data/visualisation_files/general/df_technologies.parquet' with 25403 rows
Proportion of mapped statements: 14170/25403

In [4]:
df_quinex

,publication_year,paper_id,countries,topics,concepts,source,host organization
0,2025,10.1016/j.rser.2025.115648,[],"[Catalysts for Methane Reforming, Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions]","[Jet fuel, Ethylene, Production (economics), Jet (fluid), Environmental science, Carbon fibers, Waste management, Materials science, Pulp and paper industry, Chemistry, Engineering, Catalysis, Economics, Organic chemistry, Aerospace engineering, Composite material, Composite number, Macroeconomics]",Renewable and Sustainable Energy Reviews,Elsevier BV
1,2025,10.1038/s41597-025-04550-7,"[DE, IT]","[Power Systems and Technologies, Integrated Energy Systems Optimization, Electric Power System Optimization]","[Computer science, Codebase, Grid, Workflow, Open data, Electric power transmission, Transformer, Energy planning, Context (archaeology), Electricity, Data mining, Open source, Database, Voltage, Renewable energy, Software, Engineering, Electrical engineering, Operating system, World Wide Web, Paleontology, Geometry, Mathematics, Biology]",Scientific Data,Nature Portfolio
2,2025,10.1080/09640568.2023.2287978,"[IT, ES]","[Social Acceptance of Renewable Energy, Sustainability and Climate Change Governance, Energy and Environment Impacts]","[Renewable energy, Energy transition, Photovoltaic system, Footprint, Ecological footprint, Environmental resource management, Computer science, Landscape planning, Quality (philosophy), Energy planning, Site selection, Environmental economics, Environmental science, Engineering, Geography, Sustainable development, Ecology, Economics, Archaeology, Pathology, Biology, Epistemology, Political science, Panacea (medicine), Philosophy, Alternative medicine, Law, Medicine, Electrical engineering]",Journal of Environmental Planning and Management,Taylor & Francis
3,2025,10.1016/j.trpro.2025.02.025,[],"[Maritime Transport Emissions and Efficiency, Hybrid Renewable Energy Systems, Maritime Ports and Logistics]","[Computer science, Environmental science, Risk analysis (engineering), Business]",Transportation research procedia,Elsevier BV
4,2025,10.1080/15567036.2021.1922551,"[NG, GB]","[Hybrid Renewable Energy Systems, Thermodynamic and Exergetic Analyses of Power and Cooling Systems, Integrated Energy Systems Optimization]","[Exergy, Environmental science, Renewable energy, Exergy efficiency, Process engineering, Wind power, Electricity, Nuclear engineering, Automotive engineering, Environmental engineering, Engineering, Electrical engineering]",Energy Sources Part A Recovery Utilization and Environmental Effects,Taylor & Francis
...,...,...,...,...,...,...,...
14165,2010,10.1051/epjconf/20100804001,"[AT, US, SI]","[Nuclear reactor physics and engineering, Nuclear Physics and Applications, Nuclear physics research studies]","[Nuclear data, Consistency (knowledge bases), Raw data, Computer science, Process (computing), Experimental data, Data science, Monte Carlo method, Data mining, Risk analysis (engineering), Management science, Industrial engineering, Operations research, Neutron, Artificial intelligence, Physics, Nuclear physics, Engineering, Mathematics, Statistics, Medicine, Programming language, Operating system]",EPJ Web of Conferences,EDP Sciences
14166,2010,10.5796/electrochemistry.78.970,[JP],[Climate Change and Sustainable Development],"[Environmental science, Carbon cycle, Hydrogen, Carbon fibers, Global environmental analysis, Energy consumption, Life-cycle assessment, Environmental impact assessment, Carbon dioxide, Water cycle, Environmental protection, Environmental engineering, Chemistry, Materials science, Ecology, Business, Biology, Production (economics), Economics, Macroeconomics, Organic chemistry, Marketing, Ecosystem, Composite number, Composite material]",Electrochemistry,The Electrochemical Society of Japan
14167,2010,10.1016/j.renene.2009.08.012,[IT],"[Integrated Energy Systems Optimization, Hybrid Renewable Energy Systems, Building Energy and Comfort Optimization]","[Renewable energy, Energy (signal processing), Set (abstract data type), Systems design, Work (physics), Computer science, Energy supply, Engineering, Systems engineering, Industrial engineering, Reliability engineering, Mechanical engineering, Electrical engineering, Statistics, Mathematics, Programming language]",Renewable Energy,Elsevier BV
14168,2010,10.3775/jie.89.355,[JP],"[Biofuel production and bioconversion, Forest Biomass Utilization and Management, Bioenergy crop production and management]","[Biofuel, Environmental science, Fossil fuel, Greenhouse gas, Agricultural engineering, Energy crop, Production (economics), Bioenergy, Productivity, Waste management, Engineering, Ecology, Macroeconomics, Economics, Biology]",Journal of the Japan Institute of Energy,<NA>
14169,2010,10.1103/PhysRevC.81.034319,[DE],"[Nuclear physics research studies, Astronomical and nuclear sciences, Nuclear Physics and Applications]","[Physics, Parametrization (atmospheric modeling), Giant resonance, Dipole, Neutron, Nuclear physics, Atomic physics, Atomic nucleus, Bremsstrahlung, Nucleosynthesis, Quadrupole, Isovector, Nuclear reaction, Nucleon, Radiative transfer, Electron, Quantum mechanics]",Physical Review C,American Institute of Physics

In [21]:
df = df_quinex
df = df[df["entity"] == "hydrogen"]
display(df.tail(10))
import pandas as pd
df.tail(10).to_excel("mein_dataframe.xlsx", index=False)

,publication_year,paper_id,classification,entity,property,quantity_text,value_normalized,unit_normalized,quantity_normalized,quote,temporal_scope,spatial_scope
1328811,2025,10.1002/ente.202301526,"{'rational': 'arbitrary', 'system': 'model', 'type': None}",hydrogen,pressure,= 25 bar,25.0,http://qudt.org/vocab/unit/BAR,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/BAR', 'year': None}], 'value': 25.0}], 'type': 'single_quantity'}","Starting off from hydrogen at 25 °C and 25 bar produced in the exporting country, liquid hydrogen, ammonia, liquid methane (Green LNG), methanol, and liquid organic hydrogen carrier are considered as chemical energy carries.",None,None
1328819,2025,10.1002/ente.202300981,"{'rational': 'arbitrary', 'system': 'real_world', 'type': 'specification'}",hydrogen,demand,= 700 TWh,700.0,http://qudt.org/vocab/unit/TeraW-HR,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/TeraW-HR', 'year': None}], 'value': 700.0}], 'type': 'single_quantity'}",The hydrogen demand in the five scenarios ranges from about 700 TWh for mainly industrial uses to 2800 TWh in all sectors in the EU27 + UK by 2050.,None,None
1328820,2025,10.1002/ente.202300981,"{'rational': 'arbitrary', 'system': 'real_world', 'type': 'specification'}",hydrogen,demand,= 2800 TWh,2800.0,http://qudt.org/vocab/unit/TeraW-HR,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/TeraW-HR', 'year': None}], 'value': 2800.0}], 'type': 'single_quantity'}",The hydrogen demand in the five scenarios ranges from about 700 TWh for mainly industrial uses to 2800 TWh in all sectors in the EU27 + UK by 2050.,{'year': 2050.0},None
1330447,2025,10.3390/en18010014,"{'rational': None, 'system': 'real_world', 'type': 'observation'}",hydrogen,carbon footprint,= 16.6 kg CO2-eq./kg,16.6,http://qudt.org/vocab/unit/UNITLESS,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': None, 'unit_uri': 'http://qudt.org/vocab/unit/UNITLESS', 'year': None}], 'value': 16.6}], 'type': 'single_quantity'}","The carbon footprint of hydrogen, produced by photovoltaic modules with electricity consumption from the Russian national electricity grid is 16.6 kg CO2-eq./kg, while the world average carbon footprint of photovoltaic hydrogen is 18.",None,"{'country': 'Russia', 'latitude': '64.6863136', 'longitude': '97.7453061'}"
1330756,2024,10.1016/j.accre.2024.07.013,"{'rational': None, 'system': 'real_world', 'type': 'observation'}",hydrogen,demand,= 37‒63 Mt,50.0,http://qudt.org/vocab/unit/UNITLESS,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': None, 'unit_uri': 'http://qudt.org/vocab/unit/UNITLESS', 'year': None}], 'value': 37.0}, {'modifier': '=', 'unit': [{'exponent': None, 'unit_uri': 'http://qudt.org/vocab/unit/UNITLESS', 'year': None}], 'value': 63.0}], 'type': 'range'}","On a sectoral level, by 2050, the hydrogen demand in the industrial and transportation sectors is expected to reach 37‒63 Mt and 30‒42 Mt, with a potential reduction of about 0.",{'year': 2050.0},"{'country': 'China', 'latitude': '35.0000663', 'longitude': '104.999955'}"
1337903,2023,10.1016/j.accre.2022.12.004,"{'rational': 'arbitrary', 'system': 'real_world', 'type': 'observation'}",hydrogen,demand,= 52.4 Mt,52.4,http://qudt.org/vocab/unit/UNITLESS,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': None, 'unit_uri': 'http://qudt.org/vocab/unit/UNITLESS', 'year': None}], 'value': 52.4}], 'type': 'single_quantity'}","The finding indicates that the demand for hydrogen could reach 52.4 Mt by 2050 and that the hydrogen will come from renewable power generation and nuclear energy, increasing the demand for electricity by 1884.",{'year': 2050.0},"{'country': 'China', 'latitude': '35.0000663', 'longitude': '104.999955'}"
1338360,2023,10.3390/en16093866,"{'rational': None, 'system': 'real_world', 'type': 'observation'}",hydrogen,production volume,= 18-20 million tonnes per year,19000000.0,http://qudt.org/vocab/unit/TONNE / http://qudt.org/vocab/unit/YR,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/TONNE', 'year': None} {'exponent': -1.0, 'unit_uri': 'http://qudt.org/vocab/unit/YR', 'year': None}], 'value': 18000000.0}, {'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/TONNE', 'year': None} {'exponent': -1.0, 'unit_uri': 'http://qudt.org/vocab/unit/YR', 'year': None}], 'value': 20000000.0}], 'type': 'range'}","In the Commission's 2020 hydrogen strategy, it was stated that the renewable hydrogen electrolyser capacity in the EU wanted by 2024 was 6 GW (1 million tonnes of renewable hydrogen associated, where the current hydrogen production in Europe is 18-20 million tonnes per year [3] ).",None,"{'country': 'France', 'latitude': '45.4129448', 'longitude': '-1.1438735'}"
1338386,2023,10.3390/en16093866,"{'rational': None, 'system': 'real_world', 'type': 'observation'}",hydrogen,production volume,= 18-20 million tonnes per year,19000000.0,http://qudt.org/vocab/unit/TONNE / http://qudt.org/vocab/unit/YR,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/TONNE', 'year': None} {'exponent': -1.0, 'unit_uri': 'http://qudt.org/vocab/unit/YR', 'year': None}], 'value': 18000000.0}, {'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/unit/TONNE', 'year': None} {'exponent': -1.0, 'unit_uri': 'http://qudt.org/vocab/unit/YR', 'year': None}], 'value': 20000000.0}], 'type': 'range'}","As previously commented, the European Union's goal is to produce 10 million tons of renewable H 2 per year by 2030 (where the current hydrogen production in Europe is 18-20 million tonnes per year [3] ).",None,"{'country': 'France', 'latitude': '45.4129448', 'longitude': '-1.1438735'}"
1338488,2023,10.3390/en16165881,"{'rational': 'arbitrary', 'system': 'real_world', 'type': None}",hydrogen,carbon,= zero,0.0,http://qudt.org/vocab/unit/UNITLESS,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': None, 'unit_uri': 'http://qudt.org/vocab/unit/UNITLESS', 'year': None}], 'value': 0.0}], 'type': 'single_quantity'}","Not only does Australia hope to capitalise on the emerging demand for zero-carbon hydrogen in places like Japan and South Korea by establishing a new export industry, but it also needs to mitigate the built-in carbon risk of its export revenue from coal and LNG as major customers, such as Japan and South Korea, move to decarbonise their energy systems.",{'year': 2021.0},None
1346488,2020,10.3390/app10010143,"{'rational': None, 'system': 'real_world', 'type': 'observation'}",hydrogen,system levelized costs,= 2.6–3.0 €/kg,2.8,http://qudt.org/vocab/currency/EUR / http://qudt.org/vocab/unit/KiloGM,"{'quantities': [{'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/currency/EUR', 'year': None} {'exponent': -1.0, 'unit_uri': 'http://qudt.org/vocab/unit/KiloGM', 'year': None}], 'value': 2.6}, {'modifier': '=', 'unit': [{'exponent': 1.0, 'unit_uri': 'http://qudt.org/vocab/currency/EUR', 'year': None} {'exponent': -1.0, 'unit_uri': 'http://qudt.org/vocab/unit/KiloGM', 'year': None}], 'value': 3.0}], 'type': 'range'}",The system levelized costs in the Mid Century scenario are 71–104 €/MWh for electricity and 2.6–3.0 €/kg for hydrogen—and we expect that further cost reductions are possible.,None,"{'country': None, 'latitude': '51.0000000', 'longitude': '10.0000000'}"

### **Results Metadata**

### Technologies

In [ ]:
result = discussion.get_metadata(df_quinex, [kw for kws in discussion.entity_keywords_string.values() for kw in kws], discussion.property_keywords_string["lifetime"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

technologies_df = result["filtered_df"]
discussion.print_df_sizes(technologies_df)

In [ ]:
technologies_df = discussion.perform_mapping(technologies_df, top_entities_names, entity=True, threshold=0.8)
technologies_df["entity_mapping"] = technologies_df["entity_mapping"].map(discussion.build_entity_reverse_mapping())
discussion.print_df_sizes(technologies_df)

In [ ]:
technologies_df = discussion.perform_mapping(technologies_df, top_properties_names, canonical_name="lifetime", property=True, threshold=0.75)
discussion.print_df_sizes(technologies_df)

In [ ]:
technologies_df["entity_mapping"].value_counts()

In [ ]:
technologies_df["property"].value_counts()

In [ ]:
discussion.save_df(technologies_df, "../data/visualisation_files/general/df_technologies_lifetime.parquet")

### Battery

In [4]:
result = discussion.get_metadata(df_quinex, discussion.entity_keywords_string["battery"], discussion.property_keywords_string["lifetime"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

battery_df = result["filtered_df"]
discussion.print_df_sizes(battery_df)

Total Statements: 1538
Number of Entities: 677
Number of Properties: 379

In [5]:
battery_df = discussion.perform_mapping(battery_df, top_entities_names, canonical_name="battery", entity=True, threshold=0.7)
discussion.print_df_sizes(battery_df)

Total Statements: 774
Number of Entities: 145
Number of Properties: 207

In [6]:
battery_df = discussion.perform_mapping(battery_df, top_properties_names, canonical_name="lifetime", property=True, threshold=0.7)
discussion.print_df_sizes(battery_df)

Total Statements: 329
Number of Entities: 80
Number of Properties: 15

In [7]:
discussion.save_df(battery_df, "../data/visualisation_files/battery/df_battery_lifetime2.parquet")

💾 Saved DataFrame to '../data/visualisation_files/battery/df_battery_lifetime2.parquet' with 329 rows

### Hydrogen

In [ ]:
result = discussion.get_metadata(df_quinex, discussion.entity_keywords_string["hydrogen"], discussion.property_keywords_string["cost"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

hydrogen_df = result["filtered_df"]
discussion.print_df_sizes(hydrogen_df)

In [ ]:
hydrogen_df = discussion.perform_mapping(hydrogen_df, top_entities_names, canonical_name="hydrogen", entity=True, threshold=0.8)
discussion.print_df_sizes(hydrogen_df)

In [ ]:
hydrogen_df = discussion.perform_mapping(hydrogen_df, top_properties_names, canonical_name="cost", property=True, threshold=0.75)
discussion.print_df_sizes(hydrogen_df)

In [ ]:
discussion.save_df(hydrogen_df, "../data/visualisation_files/hydrogen/df_hydrogen_cost2.parquet")

### PV

In [ ]:
result = discussion.get_metadata(df_quinex, discussion.entity_keywords_string["pv"], discussion.property_keywords_string["cost"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

pv_df = result["filtered_df"]
discussion.print_df_sizes(pv_df)

In [ ]:
pv_df = discussion.perform_mapping(pv_df, top_entities_names, canonical_name="pv", entity=True, threshold=0.8)
discussion.print_df_sizes(pv_df)

In [ ]:
pv_df = discussion.perform_mapping(pv_df, top_properties_names, canonical_name="cost", property=True, threshold=0.75)
discussion.print_df_sizes(pv_df)

In [ ]:
discussion.save_df(pv_df, "../data/visualisation_files/pv/df_pv.parquet")

### Wind Turbine

In [ ]:
result = discussion.get_metadata(df_quinex, discussion.entity_keywords_string["wind turbine"], discussion.property_keywords_string["cost"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

windturbine_df = result["filtered_df"]
discussion.print_df_sizes(windturbine_df)

In [ ]:
windturbine_df = discussion.perform_mapping(windturbine_df, top_entities_names, canonical_name="wind turbine", entity=True, threshold=0.8)
discussion.print_df_sizes(windturbine_df)

In [ ]:
windturbine_df = discussion.perform_mapping(windturbine_df, top_properties_names, canonical_name="cost", property=True, threshold=0.75)
discussion.print_df_sizes(windturbine_df)

In [ ]:
display(windturbine_df)

In [ ]:
discussion.save_df(windturbine_df, "../data/visualisation_files/windturbine/df_windturbine.parquet")

### Natural Gas

In [ ]:
result = discussion.get_metadata(df_quinex, discussion.entity_keywords_string["natural gas"], discussion.property_keywords_string["cost"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

naturalgas_df = result["filtered_df"]
discussion.print_df_sizes(naturalgas_df)

In [ ]:
naturalgas_df = discussion.perform_mapping(naturalgas_df, top_entities_names, canonical_name="natural gas", entity=True, threshold=0.8)
discussion.print_df_sizes(naturalgas_df)

In [ ]:
naturalgas_df = discussion.perform_mapping(naturalgas_df, top_properties_names, canonical_name="cost", property=True, threshold=0.75)
discussion.print_df_sizes(naturalgas_df)

In [ ]:
discussion.save_df(naturalgas_df, "../data/visualisation_files/naturalgas/df_naturalgas.parquet")

### Electrolyzer

In [ ]:
result = discussion.get_metadata(df_quinex, discussion.entity_keywords_string["electrolyzer"], discussion.property_keywords_string["cost"])

top_entities_names = result['top_entities'].index.tolist()
top_properties_names = result['top_properties'].index.tolist()

electrolyzer_df = result["filtered_df"]
discussion.print_df_sizes(electrolyzer_df)

In [ ]:
electrolyzer_df = discussion.perform_mapping(electrolyzer_df, top_entities_names, canonical_name="electrolyzer", entity=True, threshold=0.8)
discussion.print_df_sizes(electrolyzer_df)

In [ ]:
electrolyzer_df = discussion.perform_mapping(electrolyzer_df, top_properties_names, canonical_name="cost", property=True, threshold=0.75)
discussion.print_df_sizes(electrolyzer_df)

In [ ]:
discussion.save_df(electrolyzer_df, "../data/visualisation_files/electrolyzer/df_electrolyzer.parquet")